### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by BrettPlays** [Skyost/AdSky#1]
**Product concerned :**
Server

**Describe the bug :**
When I go to the installation page I get this:
`Warning: require_once(/home/unseenmc/public_html/ad/core/adsky/core/Adsky.php): failed to open stream: No such file or directory in /home/unseenmc/public_html/ad/core/Autoloader.php on line 34

Fatal error: require_once(): Failed opening required '/home/xxx/public_html/ad/core/adsky/core/Adsky.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/xxx/public_html/ad/core/Autoloader.php on line 34`

**To Reproduce :**
Steps to reproduce the behavior :
Install it?

**Expected behavior :**

**Screenshots :**
Just those errors on screen with the "installation" text at top

**Server / Desktop specs (please complete the following information) :**
don't know

**Additional context :**

**Comment by Skyost** [comment]
PHP version and AdSky installation directory ?

Do you have edited / moved anything ?

**Comment by BrettPlays** [comment]
`

Apache Version | 2.4.33
-- | --
PHP Version | 5.6.36

`
installation directory was pubic_html/ad/

No I have no edited anything.
